#############################################################
# VARIABLES
#############################################################

CHAPTERS = arithmetic integer-division logic relational

include ../../../make-lib/dirmathq.config.mk
include $(DIR_MATHQ)/make-lib/doc.variables.mk

NONEXEC = README.md $(LEAF_READMES)
EXEC += ./arithmetic/body ./integer-division/body ./logic/body ./relational/body
ALL += 

#---------------------------------------------------------------------
# RECIPES
#---------------------------------------------------------------------
include $(DIR_MATHQ)/make-lib/doc.recipes.mk



