#############################################################
# VARIABLES
#############################################################

CHAPTERS = print-debug numbers multiarrays math-functions linear-algebra vector-calculus tensors series-transforms future

include ../../make-lib/dirmathq.config.mk
include $(DIR_MATHQ)/make-lib/doc.variables.mk

NONEXEC = README.md $(LEAF_READMES)
EXEC += ./print-debug/body ./numbers/body ./multiarrays/body ./math-functions/body ./linear-algebra/body ./vector-calculus/body  ./tensors/body ./series-transforms/body ./future/body 
ALL += 

#---------------------------------------------------------------------
# RECIPES
#---------------------------------------------------------------------
include $(DIR_MATHQ)/make-lib/doc.recipes.mk

