#############################################################
# VARIABLES
#############################################################

CHAPTERS = real complex imaginary quaternion

include ../../../make-lib/dirmathq.config.mk
include $(DIR_MATHQ)/make-lib/doc.variables.mk

NONEXEC = README.md $(LEAF_READMES)
EXEC += ./real/body ./complex/body ./imaginary/body ./quaternion/body
ALL += 

#---------------------------------------------------------------------
# RECIPES
#---------------------------------------------------------------------
include $(DIR_MATHQ)/make-lib/doc.recipes.mk


