#############################################################
# VARIABLES
#############################################################

# front matter, What does it do and what does it look like?,  Getting Started, Details, Performance and Test, Contributing
CHAPTERS = license about status-release overview installation first-project user-guide benchmarks test developer-guide

include ../make-lib/dirmathq.config.mk
include $(DIR_MATHQ)/make-lib/doc.variables.mk

NONEXEC = README.md $(LEAF_READMES)
EXEC += 

#---------------------------------------------------------------------
# RECIPES
#---------------------------------------------------------------------
include $(DIR_MATHQ)/make-lib/doc.recipes.mk


