#############################################################
# VARIABLES
#############################################################

CHAPTERS = about license status-release description-examples installation first-project usage-guide benchmarks test developer-guide

include ../make-lib/dirmathq.config.mk
include $(DIR_MATHQ)/make-lib/doc.variables.mk

NONEXEC = README.md $(LEAF_READMES)
EXEC += 

#---------------------------------------------------------------------
# RECIPES
#---------------------------------------------------------------------
include $(DIR_MATHQ)/make-lib/doc.recipes.mk


