#############################################################
# VARIABLES
#############################################################

# front matter, What does it do and what does it look like?,  Getting Started, Details, Performance and Test, Contributing
CHAPTERS_AND_HEADINGS = front-matter.src.heading license about status-release \
getting-started.src.heading intro installation first-project \
using.src.heading user-guide benchmarks test \
modifying.src.heading developer-guide

include ../make-lib/dirmathq.config.mk
include $(DIR_MATHQ)/make-lib/doc.variables.mk

NONEXEC = README.md $(LEAF_READMES)
EXEC += 

#---------------------------------------------------------------------
# RECIPES
#---------------------------------------------------------------------
include $(DIR_MATHQ)/make-lib/doc.recipes.mk


