// This file was automatically generated by include/Makefile
// Do NOT manually edit. Use "make newvers" from the top level Makefile
namespace mathq {
	inline const char version[] = "v0.41.152-c++20";
};
