// This file was automatically generated by include/Makefile
// Do NOT manually edit. Use "make newvers" from the top level Makefile
namespace mathq {
	inline const char version[] = "0.42.1-alpha.046";
};
